### ISSUE TITLE
Bootstrap3 / less.php: glyphicon-halfling font files not found

### ISSUE THREAD

**Issue by telepath** [oyejorge/gpEasy-CMS#39] opened 2015-01-06 13:41 UTC
The glyphicon-halfling font files are references as relative paths in the compiles css. Since the css lies in /data/_cache/ the font files are not found.
```css
@font-face {
    font-family: "Glyphicons Halflings";
    src: url("../fonts/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"), url("../fonts/glyphicons-halflings-regular.woff") format("woff"), url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"), url("../fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular") format("svg");
}
```

**Comment by barbrick** [comment] 2015-12-04 02:06
This has been resolved since commit https://github.com/oyejorge/gpEasy-CMS/commit/c19d0ffbd5ccaa692fc1a075ec59cc6bc8bdb641 with the upgrade of bootstrap to version 3.3.5. It was caused by the less escape function around the font urls that was removed in [bootstrap version 3.2.0](https://github.com/twbs/bootstrap/blob/v3.2.0/less/glyphicons.less#L11-L18).

@oyejorge This issue should be closed or marked as resolved pending the next release.

**Comment by oyejorge** [comment] 2015-12-04 02:50
Thanks!

**Closed by oyejorge** 2015-12-04 02:50 UTC
